Public Class FrmDTransReport
    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        ' Check whether or not the Grid Control can be printed. 
        If Not GridControl1.IsPrintingAvailable Then
            MessageBox.Show("The 'DevExpress.XtraPrinting' Library is not found", "Error")
            Return
        End If
        ' Opens the Preview window. 
        GridControl1.ShowPrintPreview()
    End Sub

    Private Sub FrmDTransReport_Load(sender As Object, e As EventArgs) Handles Me.Load

        ' This line of code is generated by Data Source Configuration Wizard
        D_transactionsTableAdapter1.Fill(DTransactionDS1.d_transactions)
    End Sub
End Class