Public Class FrmTermCntRpt
    'Sub New()

    'InitializeComponent()
    ' This line of code is generated by Data Source Configuration Wizard
    'MLocTermCntTableAdapter1.Fill(DsmLocTermCnt1.MLocTermCnt)
    'End Sub

    Private Sub FrmTermCntRpt_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        MLocTermCntTableAdapter1.Fill(DsmLocTermCnt1.MLocTermCnt)
    End Sub

    Private Sub BtnPrint_Click(sender As Object, e As EventArgs) Handles BtnPrint.Click
        ' Check whether or not the Grid Control can be printed. 
        If Not GridControl1.IsPrintingAvailable Then
            MessageBox.Show("The 'DevExpress.XtraPrinting' Library is not found", "Error")
            Return
        End If
        ' Opens the Preview window. 
        GridControl1.ShowPrintPreview()
    End Sub
End Class